# Generated by Django 3.2.19 on 2023-06-01 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20230531_2001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videogame',
            old_name='console',
            new_name='consoles',
        ),
    ]
